"""主题 token 定义（深海驾驶舱 Deep Sea Cockpit 色板）。

- dark：深海声呐（深蓝底 + 声呐青 #00D4FF 主色 + 深空紫 #8B6BFF 次色）
- light：极地白鲸（浅色配套）

token 结构与 v2.22 完全一致（不增删键），只替换色值——
所有引用 token 的 UI（主窗口/对话框/面板）自动换肤，功能零改动。
"""

THEMES = {
    "light": {
        "name": "极地白鲸",
        "bg": "#e8f0f5",
        "page": "#f7fafd",
        "panel": "#ffffff",
        "surface": "#eaf3f8",
        "border": "#d8e5ed",
        "chat_bg": "#ffffff",
        "text": "#14283f",
        "text_sec": "#5c7a96",
        "accent": "#00a3c8",
        "accent_hover": "#008fb0",
        "accent_text": "#ffffff",
        "bubble_user": "#0e9dbd",
        "bubble_user_text": "#ffffff",
        "bubble_assistant": "#f2f6fa",
        "code_bg": "#eef4f7",
        "code_fg": "#1f8a70",
        "input_bg": "#ffffff",
        "input_fg": "#14283f",
        "selection": "#00a3c8",
        "thinking": "#57829c",
        "tool": "#8b6bff",
        "error": "#e5455c",
        "warning": "#e08f2e",
        "success": "#0fa878",
        "disabled": "#a9c0d4",
        "hover": "#e8f2f6",
        "note": "#57829c",
        "mention": "#00a3c8",
        "quote_bg": "#e6f6fc",
        "input_placeholder": "#8ba4bd",
    },
    "dark": {
        "name": "深海声呐",
        "bg": "#060a14",
        "page": "#0b1222",
        "panel": "#0f1a2e",
        "surface": "#15233f",
        "border": "#223357",
        "chat_bg": "#070d1a",
        "text": "#e9f1ff",
        "text_sec": "#9db0d1",
        "accent": "#00d4ff",
        "accent_hover": "#33dfff",
        "accent_text": "#05121f",
        "bubble_user": "#0f5b7d",
        "bubble_user_text": "#e9f1ff",
        "bubble_assistant": "#111c32",
        "code_bg": "#0a1322",
        "code_fg": "#a8e6c8",
        "input_bg": "#0f1a2e",
        "input_fg": "#e9f1ff",
        "selection": "#00d4ff",
        "thinking": "#5e7196",
        "tool": "#8b6bff",
        "error": "#ff5d7a",
        "warning": "#ffb454",
        "success": "#2fe6a8",
        "disabled": "#41547a",
        "hover": "#15233f",
        "note": "#5e7196",
        "mention": "#00d4ff",
        "quote_bg": "#0e2a4a",
        "input_placeholder": "#41547a",
    },
}
